# Generated by Django 3.1.3 on 2022-09-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scheduletable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.TextField()),
                ('caltype', models.CharField(max_length=6)),
                ('groupID', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('hour', models.CharField(max_length=2)),
                ('minute', models.CharField(max_length=2)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.TextField()),
                ('caltype', models.CharField(max_length=6)),
                ('password', models.TextField()),
                ('groupID', models.TextField()),
                ('authrank', models.CharField(max_length=2)),
                ('grouppassword', models.TextField()),
            ],
        ),
    ]
